### Bài 1. Tạo Tensor cơ bản
### Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.


In [1]:
import torch
a=torch.tensor(
    [[1,2,3],
    [4,5,6],],  
    dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


#### Yêu cầu: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.
##### Trả lời: tensor có kích thước là (2,3),số chiều của tensor là 2,kiểu dữ liệu là torch.int32

### Bài 2. Tạo các Tensor thường dùng Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.


In [2]:
import torch
a=torch.rand(3,4)
b=torch.randn(3,4)
c=torch.zeros(2,3)
d=torch.ones(2,3)
e=torch.eye(4)


print(a)
print(b)
print(c)
print(d)
print(e)


tensor([[0.0197, 0.2268, 0.7646, 0.0952],
        [0.0830, 0.9914, 0.3073, 0.2426],
        [0.8141, 0.2998, 0.4639, 0.1234]])
tensor([[-0.6856,  0.1684,  0.3997,  0.8562],
        [-1.7185, -1.4471, -0.6615,  0.1346],
        [-1.6109,  1.0634,  1.3200,  0.4870]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


#### Yêu cầu:
#### • Nhận xét sự khác nhau giữa torch.rand() và torch.randn().
#### • Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.

##### -Sự khác nhau giữa torch.rand() và torch.randn() là rand tạo ngẫu nhiên số ttrong khoảng 0 đến 1 chỉ chứa số dương còn randn tạo số ngẫu nhiên theo phân phối chuẩn mean =0 nên chứa cả số âm và dương

In [3]:
#tensor 5x5 toàn 10
f=torch.full((5,5),10)
print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


### Bài 3. Kiểm tra thông tin Tensor
### Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [4]:
import torch
a=torch.zeros(2,3,4)
print("tensor")
print(a)
print("shape ",a.shape)
print("size ",a.size())
print("number of dimensions ",a.ndim)
print("data type ",a.dtype)

tensor
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
shape  torch.Size([2, 3, 4])
size  torch.Size([2, 3, 4])
number of dimensions  3
data type  torch.float32


#### Yêu cầu: Giải thích ý nghĩa của torch.Size([2, 3, 4]).
##### Tensor có kích thước 3 chiều ,2 ma trận mỗi ma trận có 3 hàng và 4 cột

### Bài 4. Slicing và Indexing Truy xuất một phần dữ liệu từ Tensor nhiều chiều.


In [5]:
import torch
a=torch.randn(3,4,5)
print("original tensor")
print (a)
print("\n tensor a[1]:")
print (a[1])
print("\n tensor a[1:,2:4]:")
print(a[1:,2:4])

original tensor
tensor([[[-1.0066, -0.1275, -0.3558, -0.4311,  0.2881],
         [ 0.9241,  0.5683,  0.3308,  1.5957, -1.3755],
         [-0.1779,  0.6386,  0.0686,  1.7463, -0.1946],
         [-1.0930,  0.3371,  0.7037, -0.0078, -0.0863]],

        [[ 2.0750,  1.6716,  0.5910,  0.3441, -0.2055],
         [ 0.0239,  1.0864, -0.7753, -0.4340,  0.4933],
         [ 1.9447,  0.6627, -0.9519,  0.4948,  0.5990],
         [ 0.8266,  0.9973,  2.1439, -0.1128,  0.6180]],

        [[ 0.6752,  1.7135, -0.0256,  1.1373,  0.2297],
         [-0.8327,  0.3634, -1.1902,  0.4225,  0.2024],
         [-1.1473,  0.3116, -0.2287,  1.9414,  1.6810],
         [ 0.0804,  0.8805,  1.4143, -1.3614,  1.7530]]])

 tensor a[1]:
tensor([[ 2.0750,  1.6716,  0.5910,  0.3441, -0.2055],
        [ 0.0239,  1.0864, -0.7753, -0.4340,  0.4933],
        [ 1.9447,  0.6627, -0.9519,  0.4948,  0.5990],
        [ 0.8266,  0.9973,  2.1439, -0.1128,  0.6180]])

 tensor a[1:,2:4]:
tensor([[[ 1.9447,  0.6627, -0.9519,  0.4948,  0.5

#### Yêu cầu:
#### • Cho biết shape của a[1] và a[1:, 2:4].
#### • Thử lấy hai phần tử cuối cùng trên chiều thứ ba.
##### shape của a[1] là (4,5), shape a[1:,2:4] là (2,2,5)


In [6]:
a[:, :, 3:5]

tensor([[[-0.4311,  0.2881],
         [ 1.5957, -1.3755],
         [ 1.7463, -0.1946],
         [-0.0078, -0.0863]],

        [[ 0.3441, -0.2055],
         [-0.4340,  0.4933],
         [ 0.4948,  0.5990],
         [-0.1128,  0.6180]],

        [[ 1.1373,  0.2297],
         [ 0.4225,  0.2024],
         [ 1.9414,  1.6810],
         [-1.3614,  1.7530]]])

### Bài 5. Reshape và Flatten Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.


In [7]:
import torch
a =torch.randn(3,4)
print("original")
print(a)
print("\nflatten")
print(a.ravel())
print("\nReshape to 3x2x2 ")
print(a.reshape(3,2,2))

original
tensor([[-0.3987,  0.1289,  0.1431, -0.0369],
        [-0.1291, -1.4988, -0.7107, -2.7684],
        [ 0.3057,  0.9974, -0.5593,  1.4100]])

flatten
tensor([-0.3987,  0.1289,  0.1431, -0.0369, -0.1291, -1.4988, -0.7107, -2.7684,
         0.3057,  0.9974, -0.5593,  1.4100])

Reshape to 3x2x2 
tensor([[[-0.3987,  0.1289],
         [ 0.1431, -0.0369]],

        [[-0.1291, -1.4988],
         [-0.7107, -2.7684]],

        [[ 0.3057,  0.9974],
         [-0.5593,  1.4100]]])


#### Yêu cầu:
#### • Kiểm tra số phần tử trước và sau khi reshape.
#### • Thử reshape Tensor thành kích thước 2 × 6.
##### - số phần từ trước reshape là 3x4=12 và sau khi reshape là 3x2x2=12 đều bằng nhau

In [8]:
print("\nreshape 2x6")
print(a.reshape(2,6))


reshape 2x6
tensor([[-0.3987,  0.1289,  0.1431, -0.0369, -0.1291, -1.4988],
        [-0.7107, -2.7684,  0.3057,  0.9974, -0.5593,  1.4100]])


### Bài 6. Phép toán và nhân ma trận Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.


In [9]:
import torch
a=torch.randn(2,3)
b=torch.randn(2,3)
print("a: ")
print(a)
print("b: ")
print(b)
print("\n a+b ")
print(a+b)
print("\n a/b")
print(a/b)
print("\n a^2")
print(a**2)
print("Matrix mutiplication")
print(a @ b.T)

a: 
tensor([[ 1.0830, -0.1888,  1.8291],
        [-0.6649,  1.5527,  1.6873]])
b: 
tensor([[-0.1186,  0.6225,  0.3834],
        [-0.8398,  0.6545,  0.0516]])

 a+b 
tensor([[ 0.9644,  0.4337,  2.2125],
        [-1.5048,  2.2071,  1.7390]])

 a/b
tensor([[-9.1281, -0.3033,  4.7708],
        [ 0.7918,  2.3725, 32.6708]])

 a^2
tensor([[1.1729, 0.0356, 3.3455],
        [0.4421, 2.4108, 2.8470]])
Matrix mutiplication
tensor([[ 0.4552, -0.9386],
        [ 1.6923,  1.6617]])


#### Yêu cầu:
#### • Phân biệt phép toán a * b với a @ b.T.
#### • Cho biết shape của kết quả a @ b.T.

##### phép toán a*b là phép toán nhân 2 ma trận với a[i][j] * b[i][j] còn a @ b.T là ma trân a nhân với ma trận chuyển vị của b (b.T đảo hàng thành cột,cột thành hàng )
#### shape của a @ b.T là (2,3) @ (3,2) = (2,2)



### Bài 7. Các hàm thống kê trên Tensor Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.



In [10]:
import torch 
a= torch.randn(3,4)
print(a)
print("\n mean ")
print(torch.mean(a,dim=0))
print("\n standard devitation ")
print(torch.std(a,dim=0))
print("\n cumulative sum")
print(torch.cumsum(a,dim=0))


tensor([[ 1.0047, -1.0876,  0.7295, -1.9765],
        [ 1.0644,  0.3382, -1.6987,  0.3828],
        [ 0.1840, -0.0652,  1.7228, -0.0107]])

 mean 
tensor([ 0.7511, -0.2716,  0.2512, -0.5348])

 standard devitation 
tensor([0.4920, 0.7350, 1.7602, 1.2640])

 cumulative sum
tensor([[ 1.0047, -1.0876,  0.7295, -1.9765],
        [ 2.0692, -0.7495, -0.9692, -1.5938],
        [ 2.2532, -0.8147,  0.7536, -1.6045]])


#### Yêu cầu: • Thay dim=0 bằng dim=1 và nhận xét sự khác nhau.


In [11]:
import torch 
a= torch.randn(3,4)
print(a)
print("\n mean ")
print(torch.mean(a,dim=1))
print("\n standard devitation ")
print(torch.std(a,dim=1))
print("\n cumulative sum")
print(torch.cumsum(a,dim=1))


tensor([[-1.5099,  0.2551,  1.3632,  0.4487],
        [ 0.3406,  0.8917,  0.4822,  1.5881],
        [ 0.9626, -0.0513, -1.0983, -0.5977]])

 mean 
tensor([ 0.1393,  0.8256, -0.1962])

 standard devitation 
tensor([1.2010, 0.5594, 0.8830])

 cumulative sum
tensor([[-1.5099, -1.2548,  0.1084,  0.5571],
        [ 0.3406,  1.2322,  1.7144,  3.3025],
        [ 0.9626,  0.9114, -0.1869, -0.7846]])


##### Nhận xét; dim=0 là tính theo cột còn dim=1 là tính theo hàng

### Bài 8. Autograd cơ bản Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.


In [12]:
import torch
x=torch.tensor(
    3.6,
    requires_grad=True

)
y=x*x
y.backward()
print("x= ",x)
print("y= ",y)
print("x.grad = ",x.grad)


x=  tensor(3.6000, requires_grad=True)
y=  tensor(12.9600, grad_fn=<MulBackward0>)
x.grad =  tensor(7.2000)


In [13]:
import torch
x=torch.tensor(
    3.6,
    requires_grad=True

)
y=3*x**2+2*x+1
y.backward()
print("x= ",x)
print("y= ",y)
print("x.grad = ",x.grad)


x=  tensor(3.6000, requires_grad=True)
y=  tensor(47.0800, grad_fn=<AddBackward0>)
x.grad =  tensor(23.6000)


### Bài 9. Gradient Descent tìm hệ số đa thức Sinh dữ liệu từ đa thức y = x2 + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.


In [14]:
import numpy as np
import torch
polynomial=np.poly1d([1,2,3])
N=20
X=np.random.randn(N,1)*5
Y=polynomial(X)
XX=np.hstack([
    X*X,
    X,
    np.ones_like(X)

])
w=torch.randn(3,1,requires_grad=True)
x=torch.tensor(XX,dtype=torch.float32)
y=torch.tensor(Y,dtype=torch.float32)
optimizer=torch.optim.NAdam([w],lr=0.01)
print("intnitial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred=x @ w
    mse=torch.mean(torch.square(y-y_pred))
    mse.backward()
    optimizer.step()
print("learned coefficients:")
print(w)



intnitial coefficients:
tensor([[-0.5660],
        [ 0.1036],
        [ 0.4726]], requires_grad=True)
learned coefficients:
tensor([[1.0111],
        [2.0151],
        [2.4217]], requires_grad=True)


#### Yêu cầu:
#### • So sánh ba hệ số học được với [1, 2, 3].
#### • Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().
##### hệ số học được xấp xỉ với [1,2,3] 
##### vai trò của optimizer.zero_grad() là:Dùng để xóa gradient cũ trước mỗi lần tính toán mới
##### vai trò của mse.backward() là :Dùng để tính đạo hàm (gradient) của hàm lỗi (mse) theo các tham số w.
##### vai trò của optimizer.step là:Dùng để cập nhật các hệ số w dựa trên gradient đã tính.

### Bài 10. Giải hệ phương trình bằng Autograd Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.


In [15]:
import random
import torch
A=torch.tensor(random.random(),requires_grad=True)
B=torch.tensor(random.random(),requires_grad=True)
C=torch.tensor(random.random(),requires_grad=True)
D=torch.tensor(random.random(),requires_grad=True)
EPOCHS=2000
optimizer=torch.optim.NAdam([A,B,C,D],lr=0.01)
for _ in range(EPOCHS):
    y1=A+B-9
    y2=C-D-1
    y3=A+C-8
    y4=B-D-2
    sqerr=y1*y1+y2*y2+y3*y3+y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A= ",A)
print("B= ",B)
print("C= ",C)
print("D= ",D)

A=  tensor(4.4361, requires_grad=True)
B=  tensor(4.5638, requires_grad=True)
C=  tensor(3.5638, requires_grad=True)
D=  tensor(2.5638, requires_grad=True)


#### Yêu cầu:
#### • Kiểm tra nghiệm thu được với bốn phương trình: A+B=9, C-D=1, A+C=8, B-D=2.
#### • Nhận xét vì sao bài toán có thể có nhiều nghiệm.

##### Nghiệm tìm được thỏa mãn gần đúng cả 4 phương trình.'
##### Hệ có nhiều nghiệm vì chỉ cần chọn một biến ví dụ C thì các biến còn lại sẽ tự xác định theo. Do đó không có một nghiệm duy nhất mà có vô số nghiệm.

## 3. Bài tập áp dụng

### Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:


#### • Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.

In [16]:
import torch
X=torch.rand(24)
print(X)
print("\nreshape 4x6")
print(X.reshape(4,6))
print("\nreshape 2x12 ")
print(X.reshape(2,12))
print("\nreshape 2x3x4 ")
print(X.reshape(2,3,4))

tensor([0.2213, 0.6404, 0.6419, 0.4839, 0.3481, 0.9531, 0.1685, 0.7160, 0.3857,
        0.9265, 0.8755, 0.6081, 0.8069, 0.9198, 0.5758, 0.9942, 0.0692, 0.6404,
        0.4065, 0.2867, 0.4130, 0.9466, 0.3512, 0.8018])

reshape 4x6
tensor([[0.2213, 0.6404, 0.6419, 0.4839, 0.3481, 0.9531],
        [0.1685, 0.7160, 0.3857, 0.9265, 0.8755, 0.6081],
        [0.8069, 0.9198, 0.5758, 0.9942, 0.0692, 0.6404],
        [0.4065, 0.2867, 0.4130, 0.9466, 0.3512, 0.8018]])

reshape 2x12 
tensor([[0.2213, 0.6404, 0.6419, 0.4839, 0.3481, 0.9531, 0.1685, 0.7160, 0.3857,
         0.9265, 0.8755, 0.6081],
        [0.8069, 0.9198, 0.5758, 0.9942, 0.0692, 0.6404, 0.4065, 0.2867, 0.4130,
         0.9466, 0.3512, 0.8018]])

reshape 2x3x4 
tensor([[[0.2213, 0.6404, 0.6419, 0.4839],
         [0.3481, 0.9531, 0.1685, 0.7160],
         [0.3857, 0.9265, 0.8755, 0.6081]],

        [[0.8069, 0.9198, 0.5758, 0.9942],
         [0.0692, 0.6404, 0.4065, 0.2867],
         [0.4130, 0.9466, 0.3512, 0.8018]]])


#### • Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.

In [17]:
import torch
A=torch.rand(3,4)
B=torch.rand(3,4)
print("A+B")
print(A+B)
print("A*B")
print(A*B)
print("A/B")
print(A/B)
print("\n tính trung bình theo cột ")
print(torch.mean(A,dim=0))
print("\n tính độ lệch chuẩn theo cột")
print(torch.std(A,dim=0))

A+B
tensor([[1.1186, 1.0446, 1.3495, 0.9209],
        [1.4561, 0.5777, 0.2913, 1.2981],
        [0.8686, 0.7559, 0.2750, 0.8435]])
A*B
tensor([[0.1770, 0.2134, 0.4363, 0.0217],
        [0.4895, 0.0820, 0.0059, 0.3870],
        [0.0301, 0.0630, 0.0154, 0.0788]])
A/B
tensor([[ 0.2056,  2.7480,  1.5134, 36.9755],
        [ 1.7648,  0.7705,  0.0818,  0.5564],
        [ 0.0435,  0.1444,  2.5206,  6.8780]])

 tính trung bình theo cột 
tensor([0.3855, 0.3709, 0.3438, 0.6990])

 tính độ lệch chuẩn theo cột
tensor([0.4774, 0.3508, 0.4153, 0.2187])


#### • Cho y = 2x^2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.

In [18]:
import torch
x = torch.tensor(
    2.0,
    requires_grad=True
)
y=2*x**2+5*x+3
y.backward()
print("x= ",x)
print("y= ",y)
print("x.grad=  ",x.grad)


x=  tensor(2., requires_grad=True)
y=  tensor(21., grad_fn=<AddBackward0>)
x.grad=   tensor(13.)


#### • Thay đa thức trong Bài 9 bằng y = 2x^2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [19]:
import numpy as np
import torch
polynomial=np.poly1d([2,-3,5])
N=20
X=np.random.randn(N,1)*5
Y=polynomial(X)
XX=np.hstack([
    X*X,
    X,
    np.ones_like(X)

])
w=torch.randn(3,1,requires_grad=True)
x=torch.tensor(XX,dtype=torch.float32)
y=torch.tensor(Y,dtype=torch.float32)
optimizer=torch.optim.NAdam([w],lr=0.01)
print("intnitial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred=x @ w
    mse=torch.mean(torch.square(y-y_pred))
    mse.backward()
    optimizer.step()
print("learned coefficients:")
print(w)



intnitial coefficients:
tensor([[ 0.9776],
        [-0.4657],
        [-2.1558]], requires_grad=True)


learned coefficients:
tensor([[ 2.0757],
        [-2.7657],
        [ 0.4133]], requires_grad=True)
